# Generated by Django 2.2.13 on 2020-09-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="ip",
            field=models.GenericIPAddressField(),
        ),
    ]
