version: "3"


services:
   redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
   app:
      build:
        context: .
      ports:
      - "8000:8000"
      volumes:
      - .:/app
      env_file:
        - ./prod.env
      command: >
        sh -c "
            python manage.py migrate  &&
            python manage.py runserver 0.0.0.0:8000"
      depends_on:
        - db

   db:
      image: postgres:10-alpine
      env_file:
        - ./prod.env
   celery-worker:
      build: .
      command: celery -A news_board worker -loglevel=info
      links:
          - redis
      depends_on:
          - app
          - redis

   celery-beat:
        build: .
        command: celery -A news_board beat -loglevel=info
        links:
          - celery-worker
          - redis
        depends_on:
          - celery-worker
          - app
          - redis
